name: Solid Plyr Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Begin Test
        run: yarn test
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - run: NPM publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}